### ISSUE TITLE
Erro 503 - Servidores indisponíveis. 

### ISSUE THREAD

**Issue by dgolveira** [AMSNX/cnxpack-updater#9]
Amigos, parece que os servidores estão fora do ar. Erro 503
Versão 3.0.0

**Comment by dgolveira** [comment]
@AMSNX

**Comment by Inthurn** [comment]
Mesma coisa aqui, ficou assim depois da última att.

**Comment by dgolveira** [comment]
> Mesma coisa aqui, ficou assim depois da última att.

Descobri o problema, que provavelmente deve ser o mesmo que o seu.

Tem todo o procedimento nesse vídeo aqui do Yt 
https://youtu.be/uPCgmKFS_30

Espero que te ajude!

**Comment by Inthurn** [comment]
> > Mesma coisa aqui, ficou assim depois da última att.
> 
> Descobri o problema, que provavelmente deve ser o mesmo que o seu.
> 
> Tem todo o procedimento nesse vídeo aqui do Yt https://youtu.be/uPCgmKFS_30
> 
> Espero que te ajude!

Deu certo @dgolveira, Obrigado!
